# Generated by Django 5.2.14 on 2026-05-27 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passengers', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='mobile_contact',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_of_service',
            new_name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_notes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Stripe)'), ('paypal', 'PayPal')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxi.vehicle'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['pickup_date', 'pickup_time'], name='taxi_reserv_pickup__d0ed0d_idx'),
        ),
    ]
