# Generated by Django 5.2.14 on 2026-05-27 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_vehicle_delete_booking_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
