# Generated by Django 5.2.4 on 2025-08-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_address_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_landlord',
            new_name='is_head',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_tenant',
            new_name='is_user',
        ),
    ]
